name: build-test

on:
  push:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
