name: linux

on:
  push:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Swift Package Build
      run: swift build -v

    - name: Run tests
      run: swift test -c release
