name: macOS

on:
#  push:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Swift Package Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -c release
